name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [17]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests (100% coverage)
        run: ./gradlew test jacocoTestReport --no-daemon --info

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.os }}-${{ matrix.java-version }}
          path: |
            build/reports/tests/test/
            build/reports/jacoco/test/html/
          retention-days: 30
      
      - name: Build with Gradle
        run: ./gradlew build -x checkstyleMain --info
        
      - name: Test Parsers (Run App)
        run: ./gradlew run
        if: matrix.os == 'ubuntu-latest'

      - name: Publish JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: system-info-${{ matrix.os }}-${{ matrix.java-version }}.jar
          path: build/libs/system-info-1.0.0.jar
          retention-days: 30